### ISSUE TITLE
annoying red color when the background is transparent

### ISSUE THREAD

**Issue by hakan-demirli** [QNetITQ/WaveFox#186]
I am not sure if this is a firefox bug, wayland bug or a hyprland bug. I am on linux and using Hyprland tiling manager.

The transparent parts are getting redder and redder. Only firefox is doing that so I thought this is some CSS rule from firefox messing up the background. The color resets If I change the focus.

Firefox version: `120.0.1 (64-bit)`
Distro: Arch Linux
WM: Hyprland-git

**Comment by hakan-demirli** [comment]
Ok. I manage to reproduce the issue with this much CSS.
```css
#main-window,
#tabbrowser-tabpanels {
  background: transparent !important;
}
:root {
  background-color: transparent !important;
}
```
Here is a video demonstration of the bug.

https://github.com/QNetITQ/WaveFox/assets/78746991/b957160c-1716-4750-8464-5621375439ac




I don't really know why there is a growing red plane whenever tabs are reloading or the focus of the window is regained.
